### client di prova per testare il web service
@hostname = 192.168.56.118
@port = 8081
@host = {{hostname}}:{{port}}

###
GET http://{{host}}/ HTTP/1.1
###

GET http://{{host}}/api/help HTTP/1.1
###

GET http://{{host}}/api/chat/6 HTTP/1.1
###

POST http://{{host}}/api/chat/6 HTTP/1.1
Content-Type: application/json

{"username": "Alessa","message": "Sono allergico alle verdure"}
###
