### client di prova per testare il web service
GET http://localhost:8081/ HTTP/1.1
###

GET http://localhost:8081/api/help HTTP/1.1
###

GET http://localhost:8081/api/chat/1 HTTP/1.1
###

POST http://localhost:8081/api/chat/1 HTTP/1.1
Content-Type: application/json

{"username": "tizio","message": "Sono allergico alla verdura!"}
###
